version: '3.7'

services:
  php:
    image: php:7.2-apache
    container_name: php
    expose:
      - 80
      - 443
    volumes:
      - ./public:/var/www/html
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL

networks:
  default:
    external:
      name: nginx-proxy